{
    'name': 'Odoo Shopify Integration',
    'summary': 'Odoo Shopify Integration',
    'version': '18.0.0.0.0',
    'author': 'ICS Globe',
    'license': 'Other proprietary',
    'maintainer': 'ICS Globe',
    'website': 'https://www.yourcompany.com/',
    'depends': [
        'base',
        'product',
        'stock',
        'sale',
        'sale_management',
        'purchase',
        'delivery',
        'account',
        'account_accountant',
        'payment',
        'mail',
        'web',
        'portal',
        'hr',
        'contacts',
        'website',
        'point_of_sale',
        'pos_sale',
    ],
    'data': [
        'security/security.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        # 'data/ir_cron_data.xml',
        # 'data/ir_sequence_data.xml',
        'wizard/manual_sync_wizard_view.xml',
        'views/shopify_instance_view.xml',
        'views/shopify_order_view.xml',
        'views/shopify_customer_view.xml',
        'views/shopify_cron_view.xml',
        'views/product_product_views.xml',
        'views/product_template_views.xml',
        'views/pos_config_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'odoo_shopify_automation/static/src/overrides/control_buttons.js',
            'odoo_shopify_automation/static/src/overrides/shopify_notifications.js',
        ],
    },
    'external_dependencies': {
        'python': [
            'ShopifyAPI',
            'requests',
            'python-dateutil',
            'pandas',
            'numpy',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'installable': True,
    'application': True,
}
